server:
  port: 9080
  
spring:   application:    name: user-service
    
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/